# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QMainWindow
import pages.RegisterPage
import dao.UserDao
from connector import DatabaseDriver
import tools.MessageBoxTools
from pages.StudentsPage import StudentsPage
import  pages.TeacherPage

class LoginPage(QMainWindow):
    def __init__(self):
        super().__init__()
        self.driver = DatabaseDriver.DatabaseDriver()
        # 获取user用户的学号到学生和教师界面
        self.setupUi()
        self.show()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(654, 463)
        self.setStyleSheet("background-image: url(views/imgs/2.jpg);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 0, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 240, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.username_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.username_edit.setGeometry(QtCore.QRect(170, 130, 351, 41))
        self.username_edit.setObjectName("username_edit")
        self.password_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_edit.setGeometry(QtCore.QRect(170, 240, 351, 41))
        self.password_edit.setObjectName("password_edit")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(550, 150, 101, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.login_btn.setObjectName("login_btn")
        self.register_btn = QtWidgets.QPushButton(self.centralwidget)
        self.register_btn.setGeometry(QtCore.QRect(150, 340, 361, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.register_btn.setObjectName("register_btn")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 22))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        # 注册按钮
        self.register_btn.clicked.connect(self.register_btn_click)
        # 登录按钮
        self.login_btn.clicked.connect(self.login_btn_click)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "hznu成绩管理"))
        self.label_2.setText(_translate("MainWindow", "账号:"))
        self.label_3.setText(_translate("MainWindow", "密码:"))
        self.username_edit.setPlaceholderText(_translate("MainWindow", "请输入你的账号"))
        self.password_edit.setPlaceholderText(_translate("MainWindow", "请输入你的密码"))
        self.login_btn.setText(_translate("MainWindow", "登录"))
        self.register_btn.setText(_translate("MainWindow", "注册账号"))

    # 注册按钮
    def register_btn_click(self):
        self.register_page = pages.RegisterPage.RegisterPage()
        self.close()

    def login_btn_click(self):
        # 获取学生的学号与密码
        username: str = self.username_edit.text()
        password: str = self.password_edit.text()
        # 判断输入框中是否为空
        if username == "" or password == "":
            tools.MessageBoxTools.warning("注意", "用户名或密码不能为空!")
        else:
            # 获取用户信息(元组)
            result: tuple = dao.UserDao.login(self.driver, username, password)
            if result is None:
                # 用户不存在则警告
                tools.MessageBoxTools.warning("注意", "用户不存在或密码错误!")
            else:
                self.username = result[0]
                self.job = result[2]
                # 如果登入者为学生则进入学生界面
                if self.job == "学生":
                    self.student_page = StudentsPage(self.username)
                    self.close()
                # 如果登入者为教师则进入教师界面
                else:
                    self.teaccher_page =pages.TeacherPage.TeacherPage()
                    self.close()

