# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudentScorePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import QMainWindow
import dao.UserDao
from connector import DatabaseDriver


class StudentScorePage(QMainWindow):

    def __init__(self, username):
        super().__init__()
        self.username = username
        self.driver = DatabaseDriver.DatabaseDriver()
        self.setupUi()
        self.show()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(475, 347)
        self.setStyleSheet("background-image: url(views/imgs/3.jpg);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.chinese_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.chinese_edit.setGeometry(QtCore.QRect(180, 70, 261, 31))
        self.chinese_edit.setObjectName("chinese_edit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 190, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.math_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.math_edit.setGeometry(QtCore.QRect(180, 130, 261, 31))
        self.math_edit.setObjectName("math_edit")
        self.english_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.english_edit.setGeometry(QtCore.QRect(180, 190, 261, 31))
        self.english_edit.setObjectName("english_edit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 22))
        self.menubar.setObjectName("menubar")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

        # 获取数据库成绩
        self.result = dao.UserDao.get_user_by_all(self.driver, self.username)
        self.chinese_edit.setText(str(self.result[3]))  # 返回数据库中语文成绩
        self.math_edit.setText(str(self.result[4]))
        self.english_edit.setText(str(self.result[5]))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "体育成绩:"))
        self.label_4.setText(_translate("MainWindow", "英语成绩:"))
        self.label_2.setText(_translate("MainWindow", "高数成绩:"))
